/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.roc.netty.Thrift;


public enum Sex implements org.apache.thrift.TEnum {
  GIRL(1),
  BOY(2);

  private final int value;

  private Sex(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Sex findByValue(int value) { 
    switch (value) {
      case 1:
        return GIRL;
      case 2:
        return BOY;
      default:
        return null;
    }
  }
}
